# GitHub Pages Configuration for Tokyo Taxi AI Optimizer
# Updated: Thu Jul 31 2025 17:31 JST

# Site settings
url: https://tatsuru-kikuchi.github.io
baseurl: /tokyo-taxi-ai-optimizer
title: Tokyo Taxi AI Optimizer - App Store Assets
description: Professional iPhone App Icons and Screenshots Generator

# GitHub Pages settings
github_pages_enabled: true
rebuild_trigger: app-assets-fix-20250731

# Include HTML files for app assets
include:
  - "app-icons.html"
  - "app-screenshots.html" 
  - "app-assets.html"
  - "index.html"
  - "main.html"
  - "enhanced.html"

# Exclude backend files but include frontend assets
exclude: 
  - "backend/"
  - "docs/"
  - "k8s/"
  - "*.md"
  - "Dockerfile"
  - "docker-compose.yml"

# No Jekyll processing - serve as static files
plugins: []
markdown: kramdown
highlighter: rouge

# Force complete rebuild
cache_version: v5.0.20250731
